### ISSUE TITLE
Option to be able to unsubscribe, and also to edit preferences.

### ISSUE THREAD

**Issue by sachman** [kirankaranth1/cowin-vaccine-notifier#3]
Once registered, there is no way a subscriber can unsubscribe. This is needed, if one has no further need of the notifications. 

Also, 
To be able to add/remove pincodes, age groups, and other preferences, if any, is desired.

The link to such settings being present in every e-mail notification itself would be really practical.

**Comment by kirankaranth1** [comment]
Unsubscription is already implemented in latest emails. Re-registration with same email id merges pin codes for the next run. So both are implemented
